name: 'My Big Fat Test'
appendCommitMessageToRunName: false

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: FirstStage
  jobs:
  - job: FirstStageJob1
    steps:
    - script: |
        echo Hello, world!
        sleep 15
      displayName: 'Run a multi-line script'

- stage: SecondStage
  #dependsOn: []
  jobs:
  - job: SecondStageJob1
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        sleep 15
      displayName: 'Run a multi-line script'
  - job: SecondStageJob2
    #dependsOn: SecondStageJob1
    steps:
    - script: |
        echo This is a second job to test parallel jobs
        sleep 15
      displayName: 'Test a parallel job'
