# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: FirstStage
  jobs:
  - job: FirstStageJob1
    steps:
    - script: |
        echo Hello, world!
        sleep 30
      displayName: 'Run a multi-line script'

- stage: SecondStage
  jobs:
  - job: SecondStageJob1
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        sleep 30
      displayName: 'Run a multi-line script'
  - job: SecondStageJob2
    dependsOn: SecondStageJob1
    steps:
    - script: |
        echo This is a second job to test parallel jobs
        sleep 30
      displayName: 'Test a parallel job'
