#name: 'My Big Fat Test'
appendCommitMessageToRunName: false

trigger: 'none'
pr: 'none'

parameters:
- name: 'testparam'
  displayName: 'This is a test parameter'
  type: 'serviceConnection'
  default: 'somedefault'

pool:
  vmImage: windows-2019

resources:
  pipelines:
    - pipeline: 'somename'
      source: 'ADF Test'
      trigger: true

stages:

- stage: FirstStage
  jobs:
  - job: FirstStageJob1
    steps:
    - script: |
        echo Hello, world!
      displayName: 'Run a multi-line script'

- stage: SecondStage
  #dependsOn: []
  jobs:
  - job: SecondStageJob1
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
  - job: SecondStageJob2
    #dependsOn: SecondStageJob1
    steps:
    - script: |
        echo This is a second job to test parallel jobs
      displayName: 'Test a parallel job'
