#name: 'My Big Fat Test'
#appendCommitMessageToRunName: false

trigger: 'none'
pr: 'none'
#schedules:
#- cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
#  always: true
#  branches:
#    include:
#    - main

#parameters:
#- name: 'testparam'
#  displayName: 'This is a test parameter'
#  type: 'serviceConnection'
#  default: 'somedefault'

variables:
  a: 10

pool:
  vmImage: 'ubuntu-latest'

#resources:
#  pipelines:
#    - pipeline: 'somename'
#      source: 'ADF Test'
#      trigger: true

stages:

- stage: FirstStage
  jobs:
  - job: FirstStageJob1
    steps:
    - script: echo ${{ variables.a }}
    #- script: echo '##vso[task.setvariable variable=a]20'
    #- script: $[variables.a]

#- stage: SecondStage
#  dependsOn: []
#  jobs:
#  - job: SecondStageJob1
#    steps:
#    - script: |
#        echo Add other tasks to build, test, and deploy your project.
#        echo See https://aka.ms/yaml
#      displayName: 'Run a multi-line script'
#  - job: SecondStageJob2
#    dependsOn: SecondStageJob1
#    steps:
#    - script: |
#        echo This is a second job to test parallel jobs
#      displayName: 'Test a parallel job'
